---
- name: Create the initial ansible user config
  hosts: pi
  remote_user: pi
  vars:
    public_key: /home/ansible/.ssh/id_rsa.pub

  tasks:
  - name: Ensure python is installed on the remote host
    package:
      name: python
      state: latest

  - name: Create the ansible user on the remote host
    user:
      name: ansible
      append: yes
      
  - name: Add user "ansibleuser" to sudo
    lineinfile:
      path: /etc/sudoers.d/ansibleuser
      line: 'ansible ALL=(ALL) NOPASSWD: ALL'
      state: present
      mode: 0440
      create: yes
      validate: 'visudo -cf %s'

  - name: Copy the local ansible user public key to remote host
    authorized_key:
      user: ansible
      state: present
      key: '{{ item }}'
    with_file:
      - /home/ansible/.ssh/id_rsa.pub      

