---
- name: Configure photos app on pi
  hosts: pi
  
  tasks:
  
  - name: Download and unarchive {{ photo_package }}
    unarchive:
      src: "{{ photo_url }}{{ photo_package }}"
      dest: /media/cloud/photos
      remote_src: yes

  - name: Generate security phrase
    lineinfile:
      path: /media/cloud/photos/index.php
      regex: ".*define('SECURITY_PHRASE', '');"
      line: "        define('SECURITY_PHRASE', '{{ lookup('pipe','echo $RANDOM | md5sum | head -c 25') }}');"

  - name: Ensure PHP is installed
    package:
      name: php
      state: present

  - name: Ensure the PHP GD library (php_gd) is installed
    package:
      name: "{{ php_gd_package }}"
      state: present
      
