---
- name: Configure photos app on pi
  hosts: pi
  
  tasks:
  
  - name: Download and unarchive {{ photo_package }}
    unarchive:
      src: "{{ photo_url }}{{ photo_package }}"
      dest: /media/cloud/photos
      remote_src: yes

  - name: Change ownership on the index.php
    file:
      path: /media/cloud/photos/index.php
      owner: spenscot
      group: cloud
      mode: 0644

  - name: Ensure PHP is installed
    package:
      name: php
      state: present

  - name: Ensure the PHP GD library (php_gd) is installed
    package:
      name: "{{ php_gd_package }}"
      state: present
      
