---
- name: Configure photos app on pi
  hosts: pi
  
  tasks:
  
  - name: Download and unarchive {{ photo_package }}
    unarchive:
      src: "{{ photo_url }}{{ photo_package }}"
      dest: /media/cloud/photos
      remote_src: yes

  - name: Ensure PHP is installed
    package:
      name: php
      state: present

  - name: Ensure the PHP GD library (php_gd) is installed
    package:
      name: "{{ php_gd_package }}"
      state: present
      
  - name: Set permissions to allow auto generation of security phrase
    file:
      path: /media/cloud/photos/index.php
      mode: 0777
      
  - name: Auto generate security phrase
    uri:
      url: http://localhost/photos/index.php

  - name: Set permissions to protect the application
    file:
      path: /media/cloud/photos/index.php
      mode: 0444
      

