---
- name: Configure squid proxy on pi
  hosts: pi
  
  tasks:
  
  - name: Install {{ proxy_package }} 
    package: 
      name: "{{ proxy_service }}"
      state: present
      
  - name: Make required changes to {{ proxy_service }}
    debug:
      msg: todo
    notify: Restart Proxy
        
  - name: Open firewall port
    firewalld:
      port: "{{ proxy_port }}/tcp"
      permanent: yes
      immediate: yes
      state: enabled 

  - name: Start the {{ proxy_service }} service
    service:
      name: "{{ proxy_service }}"
      state: started
      enabled: yes

  handlers:

  - name: Restart Proxy
    service:
      name: "{{ proxy_service }}"
      state: restarted
          
