---
- name: Configure web proxy on pi
  hosts: pi

  tasks:
  
  - include_tasks: firewall.yaml

  - name: Install the {{ proxy_package }} package
    package: 
      name: "{{ proxy_package }}"
      state: present
      
  - name: Copy the {{ proxy_service }} config file
    copy:
      src: files/squid.blurdle.conf
      dest: /etc/squid/conf.d/blurdle.conf
      mode: "0600"
    notify: Restart Proxy
    
  - name: Open firewall port
    firewalld:
      port: 3128/tcp
      permanent: yes
      immediate: yes
      state: enabled 

  - name: Start the {{ proxy_service }} service
    service:
      name: "{{ proxy_service }}"
      state: started
      enabled: yes

  handlers:

  - name: Restart Proxy
    service:
      name: "{{ proxy_service }}"
      state: restarted
          
