# Cloud/NAS variables
cloud_partition: /dev/sda1
cloud_mount: /media/cloud
cloud_group: cloud
cloud_user: spenscot

# Cloud Samba varioables for the bertvv.samba role
samba_netbios_name: CLOUD
samba_server_string: 'Welcome to our cloud'
samba_workgroup: CLOUDGROUP
    
  # samba_global_include: global-include.conf

samba_load_homes: false
samba_load_printers: false
samba_create_varwww_symlinks: false

samba_log: /var/log/samba.log
samba_log_size: 60000
samba_log_level: '3 passdb:5 auth:10 winbind:2 '

  # The smbclient version of the Travis CI environment crashes when `min
  # protocol' is set:
  #    protocol negotiation failed: NT_STATUS_INVALID_NETWORK_RESPONSE
  # Uncomment the following lines if you want to test this setting locally.
  #
  # samba_server_min_protocol: SMB2
  # samba_server_max_protocol: SMB3

samba_map_to_guest: Never
samba_users:
  - name: spenscot
    password: "{{ spenscot_password }}"
        
samba_shares_root: /media/cloud
samba_shares:
  - name: our-cloud
    comment: 'Public share, writeable by all members of group ‘cloud’'
    public: 'yes'
    write_list: +cloud
    group: cloud
    setype: public_content_t
    browseable: 'yes'
  - name: photos
    comment: 'Public share, writeable by all members of group ‘cloud’'
    public: 'yes'
    write_list: +cloud
    group: cloud
    setype: public_content_t
    browseable: 'yes'
  - name: music
    comment: 'Public share, writeable by all members of group ‘cloud’'
    public: 'yes'
    write_list: +cloud
    group: cloud
    setype: public_content_t
    browseable: 'yes'
  - name: downloads
    comment: 'Public share, writeable by all members of group ‘cloud’'
    public: 'yes'
    write_list: +cloud
    group: cloud
    setype: public_content_t
    browseable: 'yes'

